apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "media-wiki.fullname" . }}-configmap
  labels: 
    {{- include "media-wiki.labels" . | nindent 4 }}
data:
  DB_SERVER: {{ printf "%s-%s" .Release.Name "mariadb" }}:3306
  DB_NAME: {{ .Values.mariadb.auth.database | b64enc | quote }}
  MW_SITE_SERVER: "http://localhost:8080"
  
