apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretprovider.name | quote }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.Sensitive.keyvault.name }}
    cloudName: AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: {{ .Values.Sensitive.keyvault.secrets.secret1 }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.Sensitive.keyvault.secrets.secret2 }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.Sensitive.keyvault.secrets.secret3 }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.Sensitive.keyvault.secrets.secret4 }}
          objectType: secret
          objectVersion: ""
    resourceGroup: {{ .Values.Sensitive.keyvault.resourcegroup }}
    subscriptionId: {{ .Values.Sensitive.subscription }}
    tenantId: {{ .Values.Sensitive.tenantid }}