apiVersion: v1
kind: Secret
metadata:
  name: {{ include "media-wiki.fullname" . }}-secret
  labels: 
    {{- include "media-wiki.labels" . | nindent 4 }}
data:
  DB_USER: {{ .Values.mariadb.auth.username | b64enc | quote }}
  DB_PASS: {{ .Values.mariadb.auth.password | b64enc | quote }}
  MW_ADMIN_NAME: {{ .Values.app_admin_name | b64enc | quote }}
  MW_ADMIN_PASS: {{ .Values.app_admin_password | b64enc | quote }}
  
